<link rel="stylesheet" href="public/asset/sass/404.css">


<div class="rail">
  <div class="stamp four">5</div>
  <div class="stamp zero">0</div>
  <div class="stamp four">5</div>
  <div class="stamp zero">0</div>
  <div class="stamp four">5</div>
  <div class="stamp zero">0</div>
  <div class="stamp four">5</div>
  <div class="stamp zero">0</div>
  <div class="stamp four">5</div>
  <div class="stamp zero">0</div>
  <div class="stamp four">5</div>
  <div class="stamp zero">0</div>
  <div class="stamp four">5</div>
  <div class="stamp zero">0</div>
  <div class="stamp four">5</div>
  <div class="stamp zero">0</div>
  <div class="stamp four">5</div>
  <div class="stamp zero">0</div>
  <div class="stamp four">5</div>
  <div class="stamp zero">0</div>
</div>
<div class="world">
  <div class="forward">
    <div class="box">
      <div class="wall"></div>
      <div class="wall"></div>
      <div class="wall"></div>
      <div class="wall"></div>
      <div class="wall"></div>
      <div class="wall"></div>
    </div>
  </div>
</div>